name: Build Patched Release

on:
  push:
    tags:
      - 'v*-patched*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to build (e.g., v1.18.6-patched)'
        required: true

permissions:
  contents: read

env:
  REGISTRY: quay.io
  # Use the org/repo name for the image
  IMAGE_PREFIX: equinixmetal/cilium

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Run unit tests
        run: |
          go test ./pkg/datapath/tables/... -v -run "NodeAddress"

  build-and-push:
    name: Build and Push ${{ matrix.name }}
    needs: test
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        include:
          - name: cilium
            dockerfile: ./images/cilium/Dockerfile

          - name: operator-generic
            dockerfile: ./images/operator/Dockerfile

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # - name: Login to quay.io
      #   uses: docker/login-action@3
      #   with:
      #     registry: quay.io
      #     username: ${{ secrets.DOCKER_USERNAME_EM_QUAY }}
      #     password: ${{ secrets.DOCKER_PASSWORD_EM_QUAY }}

      - name: Get image tag
        id: tag
        run: |
          # Get tag from git metadata.
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            TAG="${{ github.event.inputs.tag }}"
          else
            TAG="${GITHUB_REF#refs/tags/}"
          fi
          echo "tag=${TAG}" >> $GITHUB_OUTPUT

          # Create image tags for Docker image.
          echo image_tags=$${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/${{ matrix.name }}:${TAG} >> $GITHUB_OUTPUT

      - name: Get runtime image
        id: runtime
        run: |
          RUNTIME_IMAGE=$(cat .github/actions/set-runtime-image/runtime-image.txt)
          echo "image=${RUNTIME_IMAGE}" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          provenance: false
          context: .
          file: ${{ matrix.dockerfile }}
          push: false
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.tag.outputs.image_tags }}
          target: release
          build-args: |
            CILIUM_RUNTIME_IMAGE=${{ steps.runtime.outputs.image }}
            OPERATOR_VARIANT=${{ matrix.name }}
